# Configurations given in 3 groups of parameters: data, power spectra and MCMC

LoTSS_DR2:
  lss_survey_name: LoTSS_DR2
  is_optical: False
  lss_mask_name: Mask_coverage
  nside: 512
  signal_to_noise: 3
  flux_min_cut: 1
  z_tail: 1.1
  bias: 1.2
  scale_bias: True

  cosmology_name: planck
  cosmology_matter_power_spectrum: halofit
  l_range: {
#    gg: [102, 802],
#    gk: [52, 802],
    gg: [2, 66],
    gt: [2, 66],
  }
  ells_per_bin: {
#    gg: 50,
#    gk: 50,
    gg: 16,
    gt: 16,
  }

  starting_params: {bias: [2.1, 0.5], sigma8: [0.83, 0.1]}
  n_walkers: 32
  max_iterations: 5000
  continue_sampling: False


LoTSS_DR1:
  lss_survey_name: LoTSS_DR1
  is_optical: False
  nside: 512
  signal_to_noise: 0
  flux_min_cut: 0.5
  z_tail: 2.0
  bias: 2.1
  scale_bias: True

  cosmology_name: planck
  cosmology_matter_power_spectrum: halofit
  l_range: {
    gg: [2, 502],
    gk: [2, 502],
  }
  ells_per_bin: {
    gg: 50,
    gk: 50,
  }

  starting_params: {bias: [2.1, 0.5], sigma8: [0.83, 0.1]}
  n_walkers: 32
  max_iterations: 5000
  continue_sampling: False


KiDS_QSO:
  lss_survey_name: KiDS_QSO
  nside: 512
  bias: 1.6
  scale_bias: True

  cosmology_name: planck
  cosmology_matter_power_spectrum: halofit
  correlation_symbols: [gg, gk]
  l_max: {
    gg: 510,
    gk: 510,
  }
  ells_per_bin: {
    gg: 50,
    gk: 50
  }

  starting_params: {bias: [2.1, 0.5], sigma8: [0.83, 0.1]}
  n_walkers: 32
  max_iterations: 5000
  continue_sampling: False


NVSS:
  lss_survey_name: NVSS
  nside: 512
  bias: 2.18
  scale_bias: False

  cosmology_name: planck
  cosmology_matter_power_spectrum: halofit
  correlation_symbols: [gg, gt]
  l_min: {
    gg: 10,
    gt: 4,
  }
  ell_lengths: {
    gg: [8, 14, 26],
    gt: [6, 12, 24, 52],
  }

  starting_params: {bias: (2.18, 0.5)}
  n_walkers: 32
  max_iterations: 5000
  continue_sampling: False
